name: ml
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - biopython
  - click
  - matplotlib
  - mdanalysis
  - numpy=1.23.5
  - optuna
  - pandas
  - pip
  - python=3.8
  - pytorch-cpu
  - scikit-learn
  - scipy
  - seaborn
  - shap

#### GPU INSTALL ATTEMPTS ####
# conda create --name ml-gpu python=3.8
# conda activate ml-gpu
# conda install pytorch pytorch-cuda=11.8 -c pytorch -c nvidia
