name: docs
channels:
  - conda-forge
  - defaults
dependencies:
    # Base depends
  - python
  - pip

    # Package depends
  - biopython
  - lime
  - matplotlib
  - numpy
  - pandas
  - pytorch
  - seaborn
  - scikit-learn
  - shap

    # Pip-only installs
  - pip:
    - sphinx==6.0.0
    - sphinx-autoapi
    - biopandas
    - https://github.com/revitron/revitron-sphinx-theme/archive/master.zip
