name: docs
channels:
dependencies:
    # Base depends
  - python
  - pip

    # Pip-only installs
  - pip:
    - biopandas
    - lime
    - matplotlib
    - MDAnalysis
    - numpy
    - pandas
    - torch
    - scikit-learn
    - seaborn
    - shap
    - sphinx==6.2.1
    - sphinx-autoapi==3.0.0
    - https://github.com/revitron/revitron-sphinx-theme/archive/refs/tags/0.7.0.zip

