name: docs
channels:
dependencies:
    # Base depends
  - python
  - pip

    # Package depends
  - numpy
  - matplotlib
  - pandas

    # Pip-only installs
  - pip:
    - sphinx-autoapi
    - sphinx==6.0.0
    - https://github.com/revitron/revitron-sphinx-theme/archive/master.zip
